# Generated by Django 3.0.3 on 2020-02-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200228_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=' ', max_length=12),
        ),
    ]
