# Generated by Django 3.0.4 on 2020-03-25 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Semi-junior', 'Semi-junior'), ('Senior', 'Senior')], default='Estudiante', max_length=40)),
                ('nombre', models.CharField(blank=True, max_length=40)),
                ('apellido', models.CharField(blank=True, max_length=40)),
                ('foto_de_perfil', models.ImageField(blank=True, upload_to='foto_de_perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
