# Generated by Django 2.1.5 on 2020-03-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionusuario',
            name='cedula',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='celular',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='domicilio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='edad',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='email_alternativo',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, default='2020-03-26'),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default='2020-03-26'),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='informacionusuario',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('V', 'V'), ('E', 'E')], default='', max_length=1),
        ),
    ]
