# Generated by Django 2.1.5 on 2020-03-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionusuario',
            name='cargo',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Semi-junior', 'Semi-junior'), ('Senior', 'Senior')], default='Estudiante', max_length=40),
        ),
    ]
