# Generated by Django 2.1.5 on 2020-03-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='user',
        ),
    ]
