# Generated by Django 3.0.4 on 2020-03-25 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=140)),
                ('tiempo_inicio', models.DateTimeField(auto_now_add=True)),
                ('tiempo_fin', models.DateTimeField(auto_now=True)),
                ('tiempo_total', models.FloatField(default=0.0)),
                ('tiempo_total_formato', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('activa', 'Por Terminar'), ('finalizada', 'Finalizada')], max_length=10, null=True, verbose_name='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
