# Generated by Django 3.0.4 on 2020-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
