# Generated by Django 3.0.4 on 2020-03-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20200312_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
