# Generated by Django 3.0.4 on 2020-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tarea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiempo_total_formato',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tiempo_total',
            field=models.DateTimeField(null=True),
        ),
    ]
