# Generated by Django 3.0.4 on 2020-03-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_tarea_tiempo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='tiempo_total',
        ),
    ]
