# Generated by Django 3.0.4 on 2020-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_tarea_tiempo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tiempo_total',
            field=models.FloatField(default=0.0),
        ),
    ]
