# Generated by Django 3.0.4 on 2020-03-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacaciones',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Activa', 'Activa'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
